-- Sample config entries for testing the story system
-- Insert default English config values for system (guild_id = 1)

INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES

-- Field Labels
('lblStoryTitle', 'Story Title:', 'en', 1),
('lblQuickMode', 'Quick Mode?:', 'en', 1),
('lblTurnLength', 'Turn Length (hours):', 'en', 1),
('lblTimeoutReminder', 'Timeout Reminder (percent of turn length):', 'en', 1),
('lblHideTurnThreads', 'Hide Turn Threads?', 'en', 1),
('lblNoHours', 'By # of Hours (if applicable):', 'en', 1),
('lblNoWriters', '# of Writers (if applicable):', 'en', 1),
('lblYourAO3Name', 'Your AO3 name (if blank, discord display name will be used):', 'en', 1),
('lblKeepYourPrivate', 'Keep your turn threads private?:', 'en', 1),

-- Text Messages
('txtDelayStoryStart', 'Delay Story Start? (leave blank to start immediately):', 'en', 1),
('txtAndOr', 'and/or', 'en', 1),
('txtStoryCreatorAdd', 'You''ll be added as the first writer in the story. Please provide:', 'en', 1),
('txtMustBeNo', '[Field label text] must be a number.', 'en', 1),
('txtStoryThreadTitle', 'Story ID: [story_id] - [inputStoryTitle] - [story_status]', 'en', 1),
('txtTurnThreadTitle', 'Story ID: [story_id] - Turn [storyTurnNumber] - [user display name] - Ends [turnEndTime]', 'en', 1),
('txtDMTurnStart', '🎭 **Your turn has started!** You can now write your part of the story.', 'en', 1),
('txtMentionTurnStart', '🎭 **Your turn has started!** You can now write your part of the story.', 'en', 1),
('txtNormalModeWelcome', 'Welcome to your turn thread! Write your story entry here, then use the buttons below to finalize or skip your turn.', 'en', 1),
('txtQuickModeTurnStart', '🎭 **[story_title]:** [current_writer]\'s turn has started! Please use `/story write [story_id]` to submit your entry. Turn ends [turn_end_date].', 'en', 1),
('btnFinalizeEntry', '✅ Finalize Entry', 'en', 1),
('btnSkipTurn', '⏭️ Skip Turn', 'en', 1),
('txtAlreadyJoined', 'You have already joined this story!', 'en', 1),
('txtStoryJoinFail', 'You were not added to the story. Please contact an administrator.', 'en', 1),
('txtStoryActive', 'Your story is now active!', 'en', 1),
('txtMoreWritersDelay', 'This story will begin when X more writer(s) join!', 'en', 1),
('txtHoursDelay', 'This story will begin in X hours!', 'en', 1),

-- Story Status Text
('txtClosed', 'Closed', 'en', 1),
('txtActive', 'Active', 'en', 1), 
('txtPaused', 'Paused', 'en', 1),

-- Error Messages
('txtThreadCreationFailed', 'Failed to create story thread. Please contact the administrator.', 'en', 1),
('txtStoryCreated', 'Story created successfully!', 'en', 1),
('txtDMFailed', 'Could not send direct message. Check your privacy settings.', 'en', 1),

-- Write Command Text
('lblWriteEntry', 'Your Story Entry (up to 4000 characters)', 'en', 1),
('txtWriteWarning', 'TEXT IS NOT SAVED UNTIL CONFIRMED!', 'en', 1),
('txtWritePlaceholder', 'Paste your entry here...', 'en', 1),
('txtStoryNotActive', 'This story is not active. You cannot write entries for paused or closed stories.', 'en', 1),
('txtNormalModeWrite', 'This story is in normal mode. Please write your entry in your private turn thread.', 'en', 1),
('txtNotYourTurn', 'It is not your turn to write. Please wait for your turn.', 'en', 1),
('txtPendingEntryExists', 'You already have a pending entry. This will overwrite it. Continue?', 'en', 1),
('txtStoryNotFound', 'Story not found.', 'en', 1),
('txtStoryWrongGuild', 'Story not found in this server.', 'en', 1),
('txtWriteFormFailed', 'Failed to open write form. Please try again.', 'en', 1),
('txtEntryProcessFailed', 'Failed to process entry. Please try again.', 'en', 1),
('txtPreviewTitle', '📖 Entry Preview', 'en', 1),
('txtPreviewDescription', '**Review your entry before final submission:**', 'en', 1),
('txtPreviewExpires', '⏰ Expires [timestamp]', 'en', 1),
('lblYourEntry', '✍️ Your Entry:', 'en', 1),
('lblEntryContinued', '✍️ Continued ([count]):', 'en', 1),
('lblEntryStats', '📊 Entry Stats:', 'en', 1),
('txtEntryStatsTemplate', 'Characters: [char_count]/4000\nWords: ~[word_count]', 'en', 1),
('btnSubmit', 'Submit', 'en', 1),
('btnDiscard', 'Discard', 'en', 1),
('txtEntrySubmitted', '✅ **Entry submitted successfully!** The turn will advance to the next writer.', 'en', 1),
('txtEntryDiscarded', '🗑️ **Entry discarded.** You can write a new entry by using the /story write command again.', 'en', 1),
('txtActionFailed', 'Failed to process action. Please try again.', 'en', 1),
('txtDMReminder', '📝 **Pending Entry Reminder** - You have an entry waiting for confirmation.', 'en', 1),
('txtRecoveryInstructions', 'If you lost the confirmation message, use `/story myturn pending` to recover it.', 'en', 1),

-- Story List Text
('txtAllStories', 'All Stories', 'en', 1),
('txtJoinableStories', 'Joinable Stories', 'en', 1),
('txtMyStories', 'My Stories', 'en', 1),
('txtActiveStories', 'Active Stories', 'en', 1),
('txtPausedStories', 'Paused Stories', 'en', 1),
('txtNoStoriesFound', '📚 **No stories found** for filter "[filter_name]"', 'en', 1),
('txtStoriesPageTitle', '📚 [filter_title] (Page [page]/[total_pages])', 'en', 1),
('txtStoriesPageDesc', 'Showing [showing] of [total] stories', 'en', 1),
('txtCanJoin', '🟢 Can Join', 'en', 1),
('txtCannotJoin', '🔴 Cannot Join', 'en', 1),
('txtStoryListFailed', 'Failed to load stories. Please try again.', 'en', 1),
('lblStoryStatus', 'Status:', 'en', 1),
('lblStoryTurn', 'Turn:', 'en', 1),
('lblStoryWriters', 'Writers:', 'en', 1),
('lblStoryMode', 'Mode:', 'en', 1),
('lblStoryCreator', 'Creator:', 'en', 1),
('txtModeQuick', 'Quick', 'en', 1),
('txtModeNormal', 'Normal', 'en', 1),
('txtTurnWaiting', 'Waiting to start', 'en', 1),
('txtTurnOverdue', '[writer_name] (overdue)', 'en', 1),
('txtTurnTimeLeft', '[writer_name] ([hours]h left)', 'en', 1),
('txtTurnUnknown', 'Unknown', 'en', 1),

-- Join Command Text  
('lblJoinAO3Name', 'AO3 Username (optional):', 'en', 1),
('lblJoinPrivacy', 'Turn Thread Privacy:', 'en', 1),
('lblJoinNotifications', 'Notification Preference:', 'en', 1),
('txtJoinSuccess', '✅ Successfully joined "[story_title]"! You are writer #[writer_number].', 'en', 1),
('txtJoinStoryFull', '❌ This story has reached its maximum of [max_writers] writers.', 'en', 1),
('txtJoinNotAllowed', '❌ This story does not allow new writers to join after it has started.', 'en', 1),
('txtJoinStoryClosed', '❌ This story is closed and not accepting new writers.', 'en', 1),
('txtStoryFeedJoinAnnouncement', '🎭 **[joiner_name]** just joined **[story_title]**! It\'s currently **[current_writer]**\'s turn until [turn_end_date].', 'en', 1),
('txtStoryFeedCreatedPending', '📚 **New Story Created:** [story_title] by [creator_name]! Waiting for [writers_needed] more writer(s) to start.', 'en', 1),
('txtStoryFeedCreatedDelayed', '📚 **New Story Created:** [story_title] by [creator_name]! Story will start [start_time].', 'en', 1),
('txtStoryFeedCreatedActive', '📚 **New Story Created:** [story_title] by [creator_name]! Story is now active with [writer_count] writer(s).', 'en', 1),
('txtStoryFeedNowActive', '🎬 **[story_title] is now active!** [first_writer] will start the story. Turn ends [turn_end_date].', 'en', 1),
('txtStoryFeedTurnStart', '✍️ **[story_title]:** [current_writer]\'s turn has started! Turn ends [turn_end_date].', 'en', 1),
('txtJoinFormFailed', 'Failed to open join form. Please try again.', 'en', 1),
('txtJoinProcessFailed', 'Failed to process join request. Please try again.', 'en', 1),
('txtValidationErrors', '**Validation Errors:**', 'en', 1),
('txtPrivacyValidation', 'Keep Private must be "yes" or "no".', 'en', 1),
('txtQuickModeValidation', 'Quick Mode must be "off" or "on".', 'en', 1),
('txtTimeoutReminderValidation', 'Timeout Reminder must be 0, 25, 50, or 75.', 'en', 1),
('txtHideTurnThreadsValidation', 'Hide Turn Threads must be "off" or "on".', 'en', 1),
('txtFormOpenError', 'Failed to open story creation form. Please try again.', 'en', 1),
('txtFormProcessError', 'Failed to process form. Please try again.', 'en', 1),
('txtAdditionalOptionsError', 'Failed to show additional options form.', 'en', 1),
('txtStoryCreationError', 'Failed to create story. Please try again.', 'en', 1),
('txtNotificationValidation', 'Notification Preference must be "dm" or "mention".', 'en', 1),
('txtJoinPrivacyPlaceholder', 'Enter: public or private', 'en', 1),
('txtJoinNotificationPlaceholder', 'Enter: dm or mention', 'en', 1),
('txtJoinAO3Placeholder', 'Leave blank to use Discord display name', 'en', 1),
('txtQuickModePlaceholder', 'Enter: off or on', 'en', 1),
('txtTurnLengthPlaceholder', 'Enter number of hours', 'en', 1),
('txtTimeoutReminderPlaceholder', 'Enter: 0, 25, 50, or 75', 'en', 1),
('txtHideTurnThreadsPlaceholder', 'Enter: off or on', 'en', 1),
('txtDelayHoursPlaceholder', 'Enter number of hours (optional)', 'en', 1),
('txtDelayWritersPlaceholder', 'Enter number of writers (optional)', 'en', 1),
('txtAO3NamePlaceholder', 'Your AO3 username (optional)', 'en', 1),
('txtKeepPrivatePlaceholder', 'Enter: yes or no', 'en', 1),
('btnPrev', '◀️ Prev', 'en', 1),
('btnNext', 'Next ▶️', 'en', 1),
('btnFilter', '🔍 Filter', 'en', 1),
('txtQuickJoinPlaceholder', 'Quick join a story...', 'en', 1),
('txtQuickJoinDesc', '[writer_count]/[max_writers] writers • [mode] mode', 'en', 1),

-- System Configuration
('cfgLanguageCode', 'en', 'en', 1),
('cfgEntryTimeoutMinutes', '10', 'en', 1),
('cfgStoryFeedChannelId', '1234567890123456789', 'en', 1), -- Replace with actual channel ID
('cfgAdminRoleName', 'Round Robin Admin', 'en', 1); -- Admin role name for story management